### ISSUE TITLE
No results on re-execution of a TREE query using the same blank node has a object and a subject

### ISSUE THREAD

**Issue by constraintAutomaton** [comunica/comunica-feature-link-traversal#102]
I realize that when I'm running a query that has a variable that will be a blank node and that variable is reused as a subject than when I rerun the query the engine will produce no result. For illustration let's consider this query

```sparql
PREFIX tree: <https://w3id.org/tree#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
  ?node tree:relation ?relation .
  ?relation tree:node ?nextNode .
}
```

where `?relation` will be a blank node.

if instead I'm running this query

```sparql
PREFIX tree: <https://w3id.org/tree#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
  ?relation tree:node ?nextNode .
}
```
or that query 

```sparql
PREFIX tree: <https://w3id.org/tree#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
  ?node tree:relation ?relation .
}
```

I'm not having this problem. Which make me think that the reused of the blank node might be the problem.

Here a link of an [example using the engine](
https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/tree/#datasources=https%3A%2F%2Fraw.githubusercontent.com%2FTREEcg%2FTREE-LDES-visualizer%2Fmain%2Fsrc%2Fassets%2Fcht_1_2.ttl&query=PREFIX%20tree%3A%20%3Chttps%3A%2F%2Fw3id.org%2Ftree%23%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0ASELECT%20*%20WHERE%20%7B%0A%20%20%3Fnode%20tree%3Arelation%20%3Frelation%20.%0A%20%20%3Frelation%20tree%3Anode%20%3FnextNode%20.%0A%7D)

**Comment by rubensworks** [comment]
Query re-execution seems to work fine with regular link traversal AFAIK.
So this might be a tree actor-specific bug?

**Comment by constraintAutomaton** [comment]
> Query re-execution seems to work fine with regular link traversal AFAIK. So this might be a tree actor-specific bug?

At least on my end it does not.

https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/default/#datasources=https%3A%2F%2Fraw.githubusercontent.com%2FTREEcg%2FTREE-LDES-visualizer%2Fmain%2Fsrc%2Fassets%2Fcht_1_2.ttl&query=PREFIX%20tree%3A%20%3Chttps%3A%2F%2Fw3id.org%2Ftree%23%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0ASELECT%20*%20WHERE%20%7B%0A%20%20%3Fnode%20tree%3Arelation%20%3Frelation%20.%0A%20%20%3Frelation%20tree%3Anode%20%3FnextNode%20.%0A%7D

**Comment by rubensworks** [comment]
I see, so it's a higher-level problem indeed.

**Comment by rubensworks** [comment]
I just realized that this _may_ be the same problem as discovered in https://github.com/comunica/comunica/issues/1180#issuecomment-1485211746.
But this will require some work to confirm.

**Comment by rubensworks** [comment]
Ok, the changes in Comunica indeed seem to have solved this problem as well 🎉

**Comment by constraintAutomaton** [comment]
Sadly, the problem still manifests itself when we rerun the query on the demo engine.

**Comment by rubensworks** [comment]
@constraintAutomaton Could you check again with the new code in comunica v3?

**Comment by constraintAutomaton** [comment]
> @constraintAutomaton Could you check again with the new code in comunica v3?

Yes it seems to be working now!
