### ISSUE TITLE
Add 'My Solid Pod' as a dropdown datasource option

### ISSUE THREAD

**Issue by pmcb55** [comunica/comunica-feature-link-traversal#104]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

It's already nice that I can select '_My Solid **Profile**_' as a Data source from the dropdown list, but it would also be **_really_** handy if there was also a '_My Solid **Pod**_' option, which fetched the `pim:storage` triples from the currently-logged-into-Solid-Pod user's WebID Profile Document.

If it finds multiple RDF Objects for that predicate, then presumably it could add them all as data sources, and the user could manually remove any they don't want included. Although if there are multiple Pods, then they'd probably have to appear as big ugly URLs (as opposed to a single 'My Solid Pod'), so if adding multiple Pods is awkward, then (for now) it could just complain and says something really simple, like, `We currently only support 1 Pod from the user's WebID Profile Document, but we found [${pods.length}].`

This would save me from the current hassle of having to paste in a big ugly URL for the Storage Root of my user's Pod into the Data Sources text field - which is awkward, looks ugly, and is completely unnecessary (since that URL is already directly available in the WebID Profile Document that we've already read (presumably!)).

**Comment by jeswr** [comment]
> It's already nice that I can select 'My Solid Profile' as a Data source from the dropdown list, but it would also be really handy if there was also a 'My Solid Pod' option, which fetched the pim:storage triples from the currently-logged-into-Solid-Pod user's WebID Profile Document.

@pmcb55 Just tried this and I'm fairly sure that with the https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/solid-default/ build you already get the desired behavior on the "My Solid Profile" option (that engine is configured to extract the `pim:storage` triples it comes across and traverse them) so running `SELECT * WHERE { ?s ?p ?o }` returns all of the triples contained in my Pod.

**Comment by rubensworks** [comment]
Indeed, the "My Solid Profile" does already follow links to `pim:storage`, and traverses all of the pods it can find there.

Making a subselection in the case of multiple pods is not possible indeed. But since this implementation may get awkward indeed, we first need to be certain that this is a common requirement.

**Comment by rubensworks** [comment]
Closing in favor of https://github.com/comunica/jQuery-Widget.js/issues/107
