### ISSUE TITLE
Inconsistency in results when other queries are run beforehand

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica-feature-link-traversal#106]
#### Issue type:

- :bug: Bug 

____
#### Description:

To reproduce:
1. Visit https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/solid-default/ (I did this in an incognito window in Chrome).
2. Log into a Pod (I am using an ESS deployment with the account https://id.inrupt.com/jeswrtest11).
3. Execute the query `SELECT DISTINCT * WHERE { ?s a ?o }` and wait for the query to complete; 6 results were returned for my account
4. Execute the query `SELECT DISTINCT * WHERE { ?s ?p ?o }` the same 5 results are produced.

However if step 3 is _skipped_ then step 4 will return all 165 triples in my Pod before terminating execution.

____

**Comment by rubensworks** [comment]
Enabling the cache-bypass option may be a temporary workaround for this.

**Comment by rubensworks** [comment]
Fixed in https://github.com/comunica/comunica/commit/e288e461867397606500b3f09189a25c6410894e
