### ISSUE TITLE
Use `rdfs:isDefinedBy` to prevent unecessary requests on vocabularies defined using `/` semantics

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica-feature-link-traversal#141]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

As suggested in https://github.com/comunica/comunica-feature-link-traversal/issues/61#issuecomment-1327993847, I would like a feature that uses `rdfs:isDefinedBy` semantics to prevent the need to make a request to every term in vocabularies defined using `/` semantics.

**Comment by rubensworks** [comment]
Yep, makes sense to me!
This can be a pruning strategy.

(Any reason why a separate issue was created? I guess we can discuss this in #61 ?)

**Comment by jeswr** [comment]
Re-encountered this issue again yesterday (this time with ODRL) and started writing this up before I came back across #61.

I left this as a separate issue as implementing `rdfs:isDefinedBy` is a more concrete task wheras #61 is discussing a range of pruning strategies.

**Comment by rubensworks** [comment]
I think `rdfs:isDefinedBy` is the proper solution for #61. So I'm fine with merging this issue here into that one.
Let's carry on the discussion there.
