### ISSUE TITLE
'cancel' can't be called on a locked stream

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/comunica-feature-link-traversal#32]
#### Issue type:

- :bug: Bug 

____
#### Description:

On https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/default/#datasources=https%3A%2F%2Fdrive.verborgh.org%2F&query=CONSTRUCT%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D%0ALIMIT%2010000, I get # 'cancel' can't be called on a locked stream.# 'cancel' can't be called on a locked stream.

I'm worried both about the error itself, and the fact that it was "hidden" as a comment in the stream. We might want to work on UI there too.

____
#### Environment:
# 'cancel' can't be called on a locked stream.# 'cancel' can't be called on a locked stream.

**Comment by rubensworks** [comment]
The problem doesn't seem to be happening anymore in Cominica 2. I guess it was a bug in one of our (transitive) dependencies.

Created a new issue for the UI problem: https://github.com/comunica/jQuery-Widget.js/issues/106
