### ISSUE TITLE
Failed to run the command line `comunica-sparql-link-traversal-solid`

### ISSUE THREAD

**Issue by phochste** [comunica/comunica-feature-link-traversal#34]
#### Issue type:

- :bug: Bug 

____
#### Description:

When trying the install and use the example code, `comunica-sparql-link-traversal-solid` complains about:

```
Error: Cannot find module '@comunica/actor-rdf-metadata-extract-hydra-count'
```

Steps:

* `npm install @comunica/actor-init-sparql-link-traversal-solid`
* `npm install @comunica/actor-rdf-metadata-extract-hydra-count`

and execute:

```
npx comunica-sparql-link-traversal-solid  --idp https://solidcommunity.net/ \
  https://hochstenbach.solidcommunity.net/ \
  "SELECT DISTINCT * WHERE {
      ?s ?p ?o .
   }" --lenient
```

____
#### Environment:

| software            | version
| ------------------- | -------
| Comunica Init Actor | 1.22.3
| node                | v16.13.2
| npm                 | 8.1.2
| yarn                | 1.22.10
| Operating System    | darwin (Darwin 21.2.0)

#### Crash log:

https://pastebin.com/Ltcgjz5N

**Comment by rubensworks** [comment]
This might be due to only alpha releases being available for this package on npm so far.
Could you try installing for version `0.0.2-alpha.e74249a.0`?

The following should then work:
`npm install @comunica/actor-init-sparql-link-traversal-solid@0.0.2-alpha.e74249a.0`

**Comment by phochste** [comment]
This got me a step further, but still I get the same error. I tried to execute `npx comunica-sparql-link-traversal-solid` which also asked me other dependencies. I've installed them all https://pastebin.com/ByMxA5yp.

Still I get the `Error: Cannot find module '@comunica/actor-rdf-metadata-extract-hydra-count'` when I want to execute the full command `comunica-sparql-link-traversal-solid  --idp https://solidcommunity.net/ \
  https://hochstenbach.solidcommunity.net/ "SELECT DISTINCT * WHERE { ?s ?p ?o .  }" --lenient`

**Comment by rubensworks** [comment]
Could you check what happens if you checkout the code from GH, and try to run manually?

**Comment by phochste** [comment]
I could get the code working using two dependencies in a package.json and use `yarn` instead of `npm`:

```
 "dependencies": {
    "@comunica/actor-init-sparql-link-traversal-solid": "^0.0.2-alpha.e74249a.0",
    "@comunica/actor-optimize-query-operation-set-seed-sources-quadpattern-iris": "^0.0.2-alpha.e74249a.0"
  }
```

**Comment by rubensworks** [comment]
I'll try to look into fixing this soon (probably after Comunica 2.x is done).

**Comment by rubensworks** [comment]
After updating to Comunica 2, this seems to work fine again.
You may want to use `@comunica/query-sparql-link-traversal-solid` from now on (see README).
