### ISSUE TITLE
Updated Inrupt identity provider

### ISSUE THREAD

**Issue by acoburn** [comunica/comunica-feature-link-traversal#67]
#### Issue type:

- :bug: Bug 

____
#### Description:

At present, the default identity provider is `https://broker.pod.inrupt.com/`, as defined at https://github.com/comunica/comunica-feature-link-traversal/blob/b6eaad7164c46d881655d429862502ac8d6e8ba0/web-clients/settings.json#L25

In July, Inrupt updated the PodSpaces environment and uses a new OpenID Connect provider, now at `https://login.inrupt.com`. More information is available in the [blog entry](https://inrupt.com/blog/pod-spaces-upgrade).

The old OpenID Connect provider is still running (and will be for another couple weeks), but it would be appreciated if that URL could be updated to point to the new OpenID provider.

Thank you!

**Comment by rubensworks** [comment]
Thanks for the notification! Change is applied, and new versions should come live soon.
