### ISSUE TITLE
Make `source`s optional on link traversal engines

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica-feature-link-traversal#92]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

I'm finding myself writing things like

```ts
const res = await (new QueryEngine).queryBindings(/* query */,
    // We provide no sources because we are in a link traversal setting
    // @ts-ignore
    {
      '@comunica/actor-http-inrupt-solid-client-authn:session': session
    }
  );
```

a lot; it would be good to have the types reflect the fact that sources are optional in a link traversal context

**Comment by rubensworks** [comment]
Yes, fully agree!

Should be easy to do now that we have https://github.com/comunica/comunica/commit/ca7e6cf64741ec5075673dbef0374c6d033d1b9a
